# Generated by Django 4.2.1 on 2023-05-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auctionitems_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='current_bid',
            field=models.IntegerField(),
        ),
    ]
